SHOW DATABASES;
USE `day_4_9_db`;
SHOW TABLES;

SELECT * FROM users;

# TRANSACTION開始
START TRANSACTION;
UPDATE users SET name = "中山 成美" WHERE id = 1;
ROLLBACK; # TRANSACTION前に戻す
COMMIT; # 変更を反映

# 自動コミットモードの確認
SHOW VARIABLES WHERE variable_name = "autocommit";
SET AUTOCOMMIT = 0;
SELECT * FROM students ORDER BY id DESC LIMIT 10;
DELETE FROM students WHERE id = 299;
COMMIT;
SET AUTOCOMMIT = 1;








